import {
  activeStudentsIcon,
  inactiveStudentsIcon,
  activePermitsIcon,
  inactivePermitsIcon,
  activeInspectionIcon,
  inactiveInspectionIcon,
  activeProfileIcon,
  inactiveProfileIcon,
  logoutIcon,
} from "@/helpers/constants/image.constant";
import { ROUTES } from "@/helpers/constants/routes.constant";
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function classNames(...classes: unknown[]) {
  return classes.filter(Boolean).join(" ");
}

export enum INPUT_NAMES {
  USER_ID = "user_id",
  PASSWORD = "password",
  NEW_PASSWORD = "new_password",
  CONFIRM_PASSWORD = "confirm_password",
  MEANS_OF_VERIFICATION = "means_of_verification",
  EMAIL_ADDRESS = "email_address",
  PHONE_NUMBER = "phone_number",
  NIN = "nin",
  TITLE = "title",
  MOTHERS_MAIDEN_NAME = "mothers_maiden_name",
  ADDRESS = "address",
  LGA = "lga",
  MIDDLE_NAME = "middle_name",
  PLACE_OF_BIRTH = "place_of_birth",
  OCCUPATION = "occupation",
  MARITAL_STATUS = "marital_status",
  BLOOD_GROUP = "blood_group",
  NAME_OF_NEXT_OF_KIN = "name_of_next_of_kin",
  RELATIONSHIP_WITH_NEXT_OF_KIN = "relationship_with_next_of_kin",
  PHONE_NUMBER_OF_NEXT_OF_KIN = "phone_number_of_next_of_kin",
  NATIONALITY_OF_NEXT_OF_KIN = "nationality_of_next_of_kin",
  LEVEL = "level",
  DURATION = "duration",
  PERMIT_TYPE = "permit_type",
  YEARS = "years",
}

export enum TAB_TYPE {
  ALL_STUDENTS = "all-students",
  ONGOING = "ongoing",
  COMPLETED = "completed",
  ISSUED_PERMITS = "issued_permits",
  LEARNERS_PERMIT = "learners_permit",
  COVER_NOTE = "cover_note",
  ALL_APPLICATIONS = "all-applications",
  PENDING_APPLICATIONS = "pending-applications",
  ACKNOWLEDGED_APPLICATIONS = "acknowledged-applications",
}

export enum STATUS {
  ONGOING = "ongoing",
  COMPLETED = "completed",
}

export enum TransactionType {
  unit = "unit",
  newLicense = "new_license_payment",
  preRegistration = "pre_registration_payment",
  licenseReplacement = "license_replacement_payment",
  licenseRenewal = "license_renewal_payment",
  drivingSchoolApplication = "driving_school_application_payment",
  permitIssuance = "permit_payment",
}

export enum DOCUMENT_UPLOAD_TYPE {
  FACE = "face",
  SIGNATURE = "signature",
  FINGER = "finger",
  LICENSE = "license",
  CAC = "cac",
}
export enum PERMIT_TYPE {
  LEARNERS_PERMIT = "learners_permit",
  COVER_NOTE = "cover_note",
}

export enum REGISTRATION_STEPS {
  CONTACT_VERIFICATION = "contact_verification",
  VALIDATION = "validation",
  STUDENT_INFORMATION = "student_information",
  COURSE_INFORMATION = "course_information",
}

export const menuNavigation = [
  {
    name: "Students",
    href: ROUTES.STUDENTS,
    activeImage: activeStudentsIcon,
    inactiveImage: inactiveStudentsIcon,
    current: true,
  },
  {
    name: "Applications",
    href: ROUTES.APPLICATIONS,
    activeImage: activeStudentsIcon,
    inactiveImage: inactiveStudentsIcon,
    current: false,
  },
  {
    name: "Permits",
    href: ROUTES.PERMITS,
    activeImage: activePermitsIcon,
    inactiveImage: inactivePermitsIcon,
    current: false,
  },
  {
    name: "Inspection",
    href: ROUTES.INSPECTION,
    activeImage: activeInspectionIcon,
    inactiveImage: inactiveInspectionIcon,
    current: false,
  },
  {
    name: "Profile",
    href: ROUTES.PROFILE,
    activeImage: activeProfileIcon,
    inactiveImage: inactiveProfileIcon,
    current: false,
  },
  {
    name: "Log Out",
    href: ROUTES.LOGIN,
    activeImage: logoutIcon,
    inactiveImage: logoutIcon,
    current: false,
  },
];

export const meansOfVerificationOptions = [
  { value: "email_address", label: "Email Address" },
  { value: "phone_number", label: "Phone Number" },
];

export const titleOptions = [
  { value: "mr", label: "Mr" },
  { value: "mrs", label: "Mrs" },
  { value: "miss", label: "Miss" },
  { value: "ms", label: "Ms" },
];

export const occupationOptions = [
  { value: "doctor", label: "Doctor" },
  { value: "teacher", label: "Teacher" },
  { value: "engineer", label: "Engineer" },
  { value: "accountant", label: "Accountant" },
  { value: "nurse", label: "Nurse" },
  { value: "electrician", label: "Electrician" },
  { value: "architect", label: "Architect" },
  { value: "plumber", label: "Plumber" },
];

export const maritalStatusOptions = [
  { value: "single", label: "Single" },
  { value: "married", label: "Married" },
  { value: "divorced", label: "Divorced" },
  { value: "widowed", label: "Widowed" },
];

export const bloodGroupOptions = [
  { value: "o+", label: "O+" },
  { value: "o-", label: "O-" },
];

export const nextOfKinOptions = [
  { value: "sister", label: "Sister" },
  { value: "brother", label: "Brother" },
  { value: "father", label: "Father" },
  { value: "mother", label: "Mother" },
];

export const levelOptions = [
  { value: "beginner", label: "Beginner" },
  { value: "intermediate", label: "Intermediate" },
  { value: "expert", label: "Expert" },
];

export const durationOptions = [
  { value: "3", label: "3 months" },
  { value: "6", label: "6 months" },
];

export const yearOptions = [
  { value: 1, label: "1 Year" },
  { value: 2, label: "2 Years" },
  { value: 3, label: "3 Years" },
];

export const permitTypes = [
  { id: 1, name: "Learner's Permit" },
  { id: 2, name: "Cover Note" },
];

export const trainingDuration = [
  { id: 1, name: "3 months" },
  { id: 2, name: "6 months" },
];

export enum Reg {
  Pending = 0,
  Approved = 1,
  Queried = 2,
}

export const relationships = [
  { id: 1, name: "Brother" },
  { id: 2, name: "Sister" },
  { id: 3, name: "Husband" },
  { id: 4, name: "Wife" },
  { id: 5, name: "Aunt" },
  { id: 6, name: "Cousin" },
  { id: 7, name: "Uncle" },
  { id: 8, name: "Nephew" },
  { id: 9, name: "Niece" },
  { id: 10, name: "Father" },
  { id: 11, name: "Mother" },
  { id: 12, name: "Other" },
];

export const maritalStatuses = [
  { id: 1, name: "Single" },
  { id: 2, name: "Married" },
  { id: 3, name: "Divorced" },
  { id: 4, name: "Widowed" },
  { id: 5, name: "Separated" },
];

export const occupations = [
  { id: 1, name: "Accountant" },
  { id: 2, name: "Accountant assistant" },
  { id: 3, name: "Actor" },
  { id: 4, name: "Actress" },
  { id: 5, name: "Admin assistant" },
  { id: 6, name: "Admin Manager" },
  { id: 7, name: "Admin Officer" },
  { id: 8, name: "Advisor" },
  { id: 9, name: "Advocate" },
  { id: 10, name: "agent" },
  { id: 11, name: "Agronomist" },
  { id: 12, name: "Ambassador" },
  { id: 13, name: "Athlete" },
  { id: 14, name: "Author" },
  { id: 15, name: "Bank Teller" },
  { id: 16, name: "Barber" },
  { id: 17, name: "Butcher" },
  { id: 18, name: "Beekeeper" },
  { id: 19, name: "Bookseller" },
  { id: 20, name: "Broker" },
  { id: 21, name: "Business man" },
  { id: 22, name: "Cameraman" },
  { id: 23, name: "Carpenter" },
  { id: 24, name: "Cashier" },
  { id: 25, name: "Chemist" },
  { id: 26, name: "Civil Engineer" },
  { id: 27, name: "Clerk" },
  { id: 28, name: "Clockmaker" },
  { id: 29, name: "Coach" },
  { id: 30, name: "Consultant" },
  { id: 31, name: "Contractor" },
  { id: 32, name: "Cook" },
  { id: 33, name: "Coordinator" },
  { id: 34, name: "Costume designer" },
  { id: 35, name: "Customer Care agent" },
  { id: 36, name: "Customer Care assistant" },
  { id: 37, name: "Customer Care Manager" },
  { id: 38, name: "Customer Care officer" },
  { id: 39, name: "Database Developer" },
  { id: 40, name: "Database Officer" },
  { id: 41, name: "Database Technician" },
  { id: 42, name: "Dentist" },
  { id: 43, name: "Dentist Assistant" },
  { id: 44, name: "Deputy Minister" },
  { id: 45, name: "Designer" },
  { id: 46, name: "Director" },
  { id: 47, name: "Deputy Director" },
  { id: 48, name: "Doctor" },
  { id: 49, name: "Driver" },
  { id: 50, name: "Editor" },
  { id: 51, name: "Electrical Engineer" },
  { id: 52, name: "Employee" },
  { id: 53, name: "Engineer" },
  { id: 54, name: "Farmer" },
  { id: 55, name: "Film Director" },
  { id: 56, name: "Film Producer" },
  { id: 57, name: "Finance assistant" },
  { id: 58, name: "Finance Manager" },
  { id: 59, name: "Finance officer" },
  { id: 60, name: "Financial Advisor" },
  { id: 61, name: "Fire Fighter" },
  { id: 62, name: "Foreman" },
  { id: 63, name: "Fortune teller" },
  { id: 64, name: "Geologist" },
  { id: 65, name: "Goldsmith" },
  { id: 66, name: "Governer" },
  { id: 67, name: "Graphic designer" },
  { id: 68, name: "Guard" },
  { id: 69, name: "Hardware Engineer" },
  { id: 70, name: "Horticulturist" },
  { id: 71, name: "HR assistant" },
  { id: 72, name: "HR Manager" },
  { id: 73, name: "HR Officer" },
  { id: 74, name: "Human resources Advisor" },
  { id: 75, name: "Investigator" },
  { id: 76, name: "Ironsmith" },
  { id: 77, name: "IT Assistant" },
  { id: 78, name: "IT Manager" },
  { id: 79, name: "IT Officer" },
  { id: 80, name: "IT Technician" },
  { id: 81, name: "Judge" },
  { id: 82, name: "laboratory technician" },
  { id: 83, name: "landlord" },
  { id: 84, name: "Lawyer" },
  { id: 85, name: "Lecturer" },
  { id: 86, name: "Lockmaker" },
  { id: 87, name: "Logistic Assistant" },
  { id: 88, name: "Logistic Manager" },
  { id: 89, name: "Logistic Officer" },
  { id: 90, name: "lyricist" },
  { id: 91, name: "Manager" },
  { id: 92, name: "mason" },
  { id: 93, name: "Mayor" },
  { id: 94, name: "Mechanic" },
  { id: 95, name: "Mechanical Engineer" },
  { id: 96, name: "Midwife" },
  { id: 97, name: "Military Officer" },
  { id: 98, name: "Minister" },
  { id: 99, name: "Model" },
  { id: 100, name: "Money exchanger" },
  { id: 101, name: "Motors Mechanic" },
  { id: 102, name: "Nurse" },
  { id: 103, name: "Officer" },
  { id: 104, name: "Office Manager" },
  { id: 105, name: "Office Assistant" },
  { id: 106, name: "Owner" },
  { id: 107, name: "Painter" },
  { id: 108, name: "pharmacist" },
  { id: 109, name: "physiotherapist" },
  { id: 110, name: "Pilot" },
  { id: 111, name: "Politician" },
  { id: 112, name: "Plumber" },
  { id: 113, name: "Police Commander" },
  { id: 114, name: "Police officer" },
  { id: 115, name: "President" },
  { id: 116, name: "Procurement Assistant" },
  { id: 117, name: "Procurement Manager" },
  { id: 118, name: "Procurement Officer" },
  { id: 119, name: "Producer" },
  { id: 120, name: "Professor" },
  { id: 121, name: "Program Host" },
  { id: 122, name: "Program Hostess" },
  { id: 123, name: "Project Manager" },
  { id: 124, name: "Property dealer" },
  { id: 125, name: "Psychialogist" },
  { id: 126, name: "Radio Operator" },
  { id: 127, name: "reporter" },
  { id: 128, name: "Reporting assistant" },
  { id: 129, name: "Reporting Manager" },
  { id: 130, name: "Reporting Officer" },
  { id: 131, name: "Representative" },
  { id: 132, name: "Researcher" },
  { id: 133, name: "Retired officer" },
  { id: 134, name: "Sales Agent" },
  { id: 135, name: "Sales assistant" },
  { id: 136, name: "Sales Manager" },
  { id: 137, name: "Sales officer" },
  { id: 138, name: "Scientist" },
  { id: 139, name: "Security assistant" },
  { id: 140, name: "Security Manager" },
  { id: 141, name: "Security officer" },
  { id: 142, name: "Shop keeper" },
  { id: 143, name: "Singer" },
  { id: 144, name: "Software Engineer" },
  { id: 145, name: "Soldier" },
  { id: 146, name: "Sport Master" },
  { id: 147, name: "Student" },
  { id: 148, name: "Supervisor" },
  { id: 149, name: "Tailor" },
  { id: 150, name: "Teacher" },
  { id: 151, name: "Team leader" },
  { id: 152, name: "Tenant" },
  { id: 153, name: "Trader" },
  { id: 154, name: "Translator" },
  { id: 155, name: "Typist" },
  { id: 156, name: "University Teacher" },
  { id: 157, name: "Vaccinator" },
  { id: 158, name: "Watchman" },
  { id: 159, name: "Web designer" },
  { id: 160, name: "Vice President" },
  { id: 161, name: "Public Servant" },
  { id: 162, name: "Architect" },
  { id: 163, name: "Cleaner" },
  { id: 164, name: "Ambassador Foreign Service" },
  { id: 165, name: "Applicants" },
  { id: 166, name: "Artisan" },
  { id: 167, name: "Principal" },
  { id: 168, name: "Banker" },
  { id: 169, name: "Barrister" },
  { id: 170, name: "Blacksmith" },
  { id: 171, name: "Broadcaster" },
  { id: 172, name: "Bursar" },
  { id: 173, name: "Business Analyst" },
  { id: 174, name: "Businesswoman" },
  { id: 175, name: "Civil Servant" },
  { id: 176, name: "Civil Servant Foreign Service" },
  { id: 177, name: "Clergy" },
  { id: 178, name: "Counsellor" },
  { id: 179, name: "Governor" },
  { id: 180, name: "Housewife" },
  { id: 181, name: "Journalist" },
  { id: 182, name: "Marketer" },
  { id: 183, name: "Occupation Not Listed" },
  { id: 184, name: "Surveyor" },
  { id: 185, name: "Pensioner" },
  { id: 186, name: "Retired" },
  { id: 187, name: "Marketing" },
  { id: 188, name: "Musician" },
  { id: 189, name: "entrepreneur" },
  { id: 190, name: "Advertising" },
  { id: 191, name: "Self-employed" },
  { id: 192, name: "Applicant" },
  { id: 193, name: "Pastor" },
  { id: 194, name: "CEO" },
  { id: 195, name: "Photographer" },
  { id: 196, name: "Legal Practitioner" },
  { id: 197, name: "Public Health" },
  { id: 198, name: "Programme Officer" },
  { id: 199, name: "Technician" },
  { id: 200, name: "Investment Banking" },
  { id: 201, name: "Humanitarian" },
  { id: 202, name: "Footballer" },
  { id: 203, name: "Tiler" },
  { id: 204, name: "Health Officer" },
  { id: 205, name: "Unemployed" },
  { id: 206, name: "Nutritionist" },
  { id: 207, name: "Librarian" },
  { id: 208, name: "Steward" },
  { id: 209, name: "Artist" },
  { id: 210, name: "Auditor" },
  { id: 211, name: "babysitter" },
  { id: 212, name: "Waiter" },
  { id: 213, name: "Analyst" },
  { id: 214, name: "Operator" },
  { id: 215, name: "Economist" },
  { id: 216, name: "Tax Administrator" },
  { id: 217, name: "Instructor" },
  { id: 218, name: "IT Consultant" },
  { id: 219, name: "Quality Assurance Analyst" },
  { id: 220, name: "IT Student" },
  { id: 221, name: "Baker" },
  { id: 222, name: "Project Coordinator" },
  { id: 223, name: "Program Manager" },
  { id: 224, name: "Store Manager" },
  { id: 225, name: "Corp Member" },
  { id: 226, name: "Catering And Hotel Management" },
  { id: 227, name: "Freight & Logistics" },
  { id: 228, name: "Finance Director" },
  { id: 229, name: "Intern" },
  { id: 230, name: "Store Officer" },
  { id: 231, name: "Human Resource Manager" },
  { id: 232, name: "Imam" },
  { id: 233, name: "Managing Director" },
  { id: 234, name: "Pension Manager" },
  { id: 235, name: "Publisher" },
  { id: 236, name: "Electrician" },
];

export const bloodGroups = [
  { id: 1, name: "A+" },
  { id: 2, name: "A-" },
  { id: 3, name: "B+" },
  { id: 4, name: "B-" },
  { id: 5, name: "AB+" },
  { id: 6, name: "AB-" },
  { id: 7, name: "O+" },
  { id: 8, name: "O-" },
];

export const genders = [
  { id: 1, name: "Male" },
  { id: 2, name: "Female" },
];

export const salutations = [
  { id: 1, name: "Mr." },
  { id: 2, name: "Mrs." },
  { id: 3, name: "Ms." },
  { id: 4, name: "Miss" },
  { id: 5, name: "Alhaji" },
  { id: 6, name: "Alhaja" },
  { id: 7, name: "Hajiya" },
  { id: 8, name: "Senator" },
  { id: 9, name: "Pastor" },
  { id: 10, name: "Dr." },
  { id: 11, name: "Deacon" },
  { id: 12, name: "Mallam" },
  { id: 14, name: "Bishop" },
  { id: 15, name: "Engr." },
  { id: 16, name: "Elder" },
  { id: 17, name: "Evangelist" },
  { id: 18, name: "HRH." },
  { id: 19, name: "HON." },
  { id: 20, name: "Prince" },
  { id: 21, name: "Prof." },
  { id: 22, name: "Rev." },
  { id: 23, name: "Oba" },
  { id: 24, name: "Obi" },
  { id: 25, name: "Chief" },
  { id: 26, name: "Surveyor" },
  { id: 27, name: "Otunba" },
  { id: 28, name: "ARCH." },
  { id: 29, name: "CAPTAIN" },
  { id: 30, name: "Master" },
  { id: 31, name: "Gen." },
  { id: 32, name: "Justice" },
];
